services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - H2_CONSOLE_ENABLED=true
      - H2_CONSOLE_PATH=/h2-console
    networks:
      - app-network

networks:
  app-network:
    driver: bridge